### ISSUE TITLE
Firepad.TextOperation.fromJSON or something like it?

### ISSUE THREAD

**Issue by edanweis** [interviewstreet/firepad-x#46]
How can we apply operational transformations as in [text-operation.js](https://github.com/FirebaseExtended/firepad/blob/v1.5.11/lib/text-operation.js) from [FirebaseExtended/firepad](https://github.com/FirebaseExtended/firepad)?

I would like to apply a history of revisions up to a timestamp as demonstrated in this tutorial:
[logicboard.com/blog/code-replay](https://logicboard.com/blog/code-replay)

But there is no `Firepad.TextOperation.fromJSON` available to compose a TextOperation.

**Comment by chaitanyapandit** [comment]
Hi @edanweis developer of Logicboard here, TextOperation.fromJSON is defined here: https://github.com/FirebaseExtended/firepad/blob/master/lib/text-operation.js#L179

**Comment by aditya211935** [comment]
@edanweis You can find TextOperation.fromJSON in https://github.com/interviewstreet/firepad-x/blob/4c94ce5c31f4387609c0b3b83d46c7a86c907d36/src/text-operation.ts#L926-L955
