### ISSUE TITLE
Allow setting arbitrary user properties

### ISSUE THREAD

**Issue by MasterOdin** [interviewstreet/firepad-x#71]
It would be nice to be able to set arbitrary properties for a user who connects to firepad. In our case, we would like to add a picture field for each user. I could see other people wanting different things, and so hence the desire for allowing setting these fields arbitrarily.

A suggested API would be modifying `IFirepadConstructorOptions` to have a new `user: Record<string, string>` field, which when set, and would be set into the `this._userRef` field, e.g.

```js
Object.entries(user).forEach(([key, value]) => this._userRef.child(key).set(value)
```

Assuming allowing for a more breaking change, would perhaps be nice to fold in `userId`, `userName`, and `userColor` into the above `user` object:

```ts
interface IUser {
  id: string;
  name: string;
  color: string;
  [key: string]: string;
}
```

and then could simplify saving to `this._userRef.set(user)`, though keeping in place existing validation for those required fields.

**Comment by aditya211935** [comment]
Thanks for the suggestion @MasterOdin! Firepad-x is supposed to be a library for collaboration and as such, it'll need to keep some internal state to do so (OT operations, user indicators). We don't want consumers of the library to depend on the internal state of firepad-x, and as such, the `setUserId` set of functions are necessarily opaque (they allow you to set user ID, but not read firepad's user ID).
For your usecase, if you want each user object to have additional fields, I'd recommend creating another key in your firebase DB, just beside the databaseRef that you pass to firebase. You can call it `userData`, and `userId` can be key of objects inside this, and you can also pass this userId to firepad constructor.
```
{
    [databaseRef]: {
        users: {
            [userId]: {
                ...<firepad's internal state>
            }
        }
    },
    userData: {
        [userId]: {
            ...<Your application's state for userId>
        }
    }
}
```
Hope this helps!
